#include "Interactive/Widgets/ClipPlane.h"
#include "Interactive/Im3DRenderer.h"
#include "Interactive/MathUtil/MathUtil.h"
#include "renderer/SceneView.h"
#include <Core/Rendering/EngineBufferRenderFeature.h>
#include "Interactive/Interactive/ExecuteCommand.h"
#include "Interactive/Interactive/RenderWindowInteractor.h"
#include "core/component/CTopoShape.h"
#include "TopoShape.h"
#include "core/component/TopoShapeActor.h"
#include "Interactive/GizmoBehaviour.h"
#include "Qtimgui/imgui/imgui.h"
#include "core/ViewTool.h"

#include <Core/ECS/Components/CMaterialRenderer.h>
#include "Core/Global/ServiceLocator.h"
#include <tracy/Tracy.hpp>
namespace MOON {

	struct PickMeshInfo {
		std::string blockName;
		ClipPlane::PickMeshId meshId;
		Maths::FVector4 blockColor;
	};
	static PickMeshInfo table[9] = {
		{"YArrow",ClipPlane::PickMeshId::YAxis,{ 0,1,0,1 }},
		{"XArrow",ClipPlane::PickMeshId::XAxis,{ 1,0,0,1 }},
		{"ZArrow",ClipPlane::PickMeshId::ZAxis,{ 0,0,1,1 }},
		{"XPlane",ClipPlane::PickMeshId::XNormalPlane,{ 1,0,0,1 }},
		{"YPlane",ClipPlane::PickMeshId::YNormalPlane,{ 0,1,0,1 }},
		{"ZPlane",ClipPlane::PickMeshId::ZNormalPlane,{ 0,0,1,1 }},
		{"XAxis",ClipPlane::PickMeshId::XNormalRotate ,{ 1,0,0,1 }},
		{"YAxis",ClipPlane::PickMeshId::YNormalRotate,{ 0,1,0,1 }},
		{"ZAxis",ClipPlane::PickMeshId::ZNormalRotate,{ 1,0,1,1 }}
	};
	static int meshInfoCnt = 9;
	Maths::FVector4 hotColor = { 0.1,1.0,1.0,1 };
	Maths::FVector4 activeColor = { 1,1,0,1 };

		// ---------------------------------------------------------------------------
	// Fixed-scale gizmo principle (matches the FIXED_SCALE feature of
	// GizmoCell.ovfx)
	// ---------------------------------------------------------------------------
	// The clip-plane widget meshes are drawn through the FIXED_SCALE shader
	// path: every model-space vertex is scaled by
	//
	//   perspective: ratio = 400 * |viewZ| / (proj[1][1] * screenHeight)
	//   ortho:       ratio = 400 / (proj[1][1] * screenHeight)
	//
	// where viewZ is the vertex depth in view space and proj[1][1] is the
	// vertical field-of-view term of the projection matrix. After applying this
	// scale, one mesh unit projects to exactly 200 pixels on screen, no matter
	// how far the camera is:
	//
	//   ndcY   = proj[1][1] * (ratio * y) / viewZ
	//          = proj[1][1] * (400 * viewZ / (proj[1][1] * screenHeight)) * y / viewZ
	//          = 400 * y / screenHeight
	//   pixels = ndcY * screenHeight / 2 = 200 * y
	//
	// The rotation path (the arc swept while dragging a rotation handle) is
	// generated by GizmoAxisRotate::getRotationArc() with a fixed world-space
	// radius (the unit reference direction). Without extra scaling the arc
	// would grow/shrink with the camera distance while the widget itself stays
	// constant, so it would drift away from the rotation ring. The arc radius
	// is therefore multiplied by the same ratio plus the widget's own model
	// scale and the ring radius of the gizmo mesh:
	//
	//   arcRadius = ratio * kGizmoScale * kRingMeshRadius
	//
	//   0.1  = the model scale passed to drawOneMesh() for "TransformAxis"
	//   7.93 = the ring radius of the gizmo mesh: the cylinder (res.obj) is
	//          placed at x ~ 7.93 in the TransformAxis() polygon, so rotating
	//          any axis sweeps that cylinder along a ring of that radius.
	//
	// If the gizmo mesh or its draw scale changes, update the constants in
	// onUpdate() accordingly.
	// ---------------------------------------------------------------------------
	static float ComputeGizmoFixedScaleRatio(
		Editor::Panels::SceneView& p_view,
		const Eigen::Vector3f& p_worldPos)
	{
		const auto* camera = p_view.GetCamera();
		if (!camera) return 1.0f;

		const auto& projection = camera->GetProjectionMatrix();
		const float proj11 = projection(1, 1);
		const float screenHeight = static_cast<float>(p_view.GetRenderer().GetFrameDescriptor().renderHeight);
		if (proj11 <= 0.0f || screenHeight <= 0.0f) return 1.0f;

		if (camera->GetProjectionMode() == ::Rendering::Settings::EProjectionMode::ORTHOGRAPHIC)
		{
			return 400.0f / (proj11 * screenHeight);
		}

		const Maths::FVector3 viewPos = camera->GetViewMatrix().MulPoint(
			Maths::FVector3{ p_worldPos.x(), p_worldPos.y(), p_worldPos.z() });
		const float depth = std::abs(viewPos.z);
		return 400.0f * depth / (proj11 * screenHeight);
	}
class ClipPlane::ClipPlaneInternal {
	public:
		ClipPlaneInternal(ClipPlane* clip) :mSelf(clip) {
		}
		~ClipPlaneInternal() {
		}
	private:
		
		friend class ClipPlane;
		ClipPlane* mSelf = nullptr;
		Eigen::Vector3f center = { 0,0,0 };
		Eigen::Vector3f normal = { 0,1,0 };
		Eigen::Vector3f xAxis = { 1,0,0 };
		Eigen::Vector3f yAxis = { 0,1,0 };
		Eigen::Vector3f zAxis = { 0,0,1 };
		bool updateEngineUbo = false;
		GizmoAxisTranslate transLatePick;
		GizmoPlaneTranslate planeTPick;
		GizmoAxisRotate axisRPick;
	};

	ClipPlane::ClipPlane(const std::string& name) :EventWidget(name)
		, m_internal(new ClipPlaneInternal(this)), mState(Stop) {

	}
	ClipPlane::~ClipPlane()
	{
		delete m_internal;
	}
	void ClipPlane::onUpdate()
	{
		if (mState == AxisR)
		{
			float angle = m_internal->axisRPick.getRotationAngle();
			float degree = -angle * 180 / 3.14159265358979323846f;
			std::string text = std::to_string(degree) + " degree\n";
			auto pos = renderer->getFrameParam().cursor;
			ImGui::GetForegroundDrawList()->AddText({ pos.x(),pos.y() - 20 }, IM_COL32(255, 255, 0, 255), text.c_str());
			auto seg = m_internal->axisRPick.getRotationArc();
			if (seg.size() > 0) {
				// The rotation path must keep a constant screen size like the
				// gizmo meshes: scale the arc radius with the camera distance
				// using the same FIXED_SCALE factor as GizmoCell.ovfx.
				const float ratio = ComputeGizmoFixedScaleRatio(*m_sceneView, m_internal->center);
				constexpr float kGizmoScale = 0.1f;      // drawOneMesh scale below
				constexpr float kRingMeshRadius = 7.93f; // res.obj cylinder offset in TransformAxis()
				const float arcScale = ratio * kGizmoScale * kRingMeshRadius;
				const Eigen::Vector3f& arcCenter = m_internal->center;
				for (auto& point : seg)
				{
					point = arcCenter + (point - arcCenter) * arcScale;
				}
				renderer->pushColor({ 255,255,255,0 });
				for (int i = 0; i < seg.size() - 1; i++) {
					renderer->drawLine(seg[i], seg[i + 1], 5);
				}
				renderer->popColor();
				renderer->pushColor({ 255,0,255,255 });
				renderer->drawLine(seg[0], m_internal->center, 4);
				renderer->drawLine(seg.back(), m_internal->center, 4);
				renderer->popColor();
			}
		}
		renderer->drawOneMesh(
			m_internal->center,
			RotationMatrix(m_internal->xAxis, m_internal->yAxis, m_internal->zAxis),
			Eigen::Vector3f{ 0.1f,0.1f,0.1f },
			"TransformAxis");
		if (m_internal->updateEngineUbo)
		{
			m_internal->updateEngineUbo = false;
			auto& feature = m_sceneView->GetRenderer().GetFeature<::Core::Rendering::EngineBufferRenderFeature>();
			feature.SetClipPlane(
				m_internal->zAxis.x(),
				m_internal->zAxis.y(),
				m_internal->zAxis.z(),
				-m_internal->zAxis.dot(m_internal->center)
			);
		}
	}

	void ClipPlane::onSetActive(bool flag)
	{
		if (flag) {
			 auto center=m_sceneView->GetScene()->GetSceneBoundingBox().center();
			 m_internal->center = Eigen::Vector3f(center.x,center.y,center.z);
		}
	}

	Maths::FVector4 ClipPlane::getClipPlane()
	{
		return Maths::FVector4(
			m_internal->zAxis.x(),
			m_internal->zAxis.y(),
			m_internal->zAxis.z(),
			m_internal->zAxis.dot(m_internal->center)
		);
	}

	void ClipPlane::onLeftMousePressed()
	{
		if (mState == Hot) {
			bool active = false;
			if (table[mPickMesh].meshId == PickMeshId::YAxis || table[mPickMesh].meshId == PickMeshId::XAxis || table[mPickMesh].meshId == PickMeshId::ZAxis) {
				mState = AxisT;
				Eigen::Vector3f axis = table[mPickMesh].meshId == PickMeshId::YAxis ?
					m_internal->yAxis : (table[mPickMesh].meshId == PickMeshId::XAxis ? m_internal->xAxis : m_internal->zAxis);
				m_internal->transLatePick.startPick(axis, m_internal->center);
				active = true;
			}
			else if (table[mPickMesh].meshId == PickMeshId::XNormalPlane || table[mPickMesh].meshId == PickMeshId::YNormalPlane || table[mPickMesh].meshId == PickMeshId::ZNormalPlane) {
				mState = PlaneT;
				Eigen::Vector3f normal = table[mPickMesh].meshId == PickMeshId::XNormalPlane ?
					m_internal->xAxis : (table[mPickMesh].meshId == PickMeshId::YNormalPlane ? m_internal->yAxis : m_internal->zAxis);
				float w = -m_internal->center.dot(normal);
				Eigen::Vector4f planeEqu = { normal.x(),normal.y(),normal.z(),w };
				m_internal->planeTPick.startPick(planeEqu, m_internal->center);
				active = true;
			}
			else if (table[mPickMesh].meshId == PickMeshId::XNormalRotate || table[mPickMesh].meshId == PickMeshId::YNormalRotate || mPickMesh == PickMeshId::ZNormalRotate) {
				mState = AxisR;
				Eigen::Vector3f normal = table[mPickMesh].meshId == PickMeshId::XNormalRotate ?
					m_internal->yAxis : (table[mPickMesh].meshId == PickMeshId::YNormalRotate ? m_internal->zAxis : m_internal->xAxis);
				Eigen::Vector3f refDir = table[mPickMesh].meshId == PickMeshId::XNormalRotate ?
					m_internal->xAxis : (table[mPickMesh].meshId == PickMeshId::YNormalRotate ? m_internal->yAxis : m_internal->zAxis);

				m_internal->axisRPick.startPick(normal, m_internal->center, refDir, m_internal->center + refDir);
				active = true;
			}
			if (active) {
				TransformAxis().setBlockColor(TransformAxis().getBlockId(table[mPickMesh].blockName), activeColor);
			}
		}
	}

	void ClipPlane::onLeftMouseReleased()
	{
		if (mState == AxisT || mState == PlaneT || mState == AxisR) {
			mState = Hot;
			TransformAxis().setBlockColor(TransformAxis().getBlockId(table[mPickMesh].blockName), hotColor);
			PickMeshId id = table[mPickMesh].meshId;
			bool updateFlag = (id != PickMeshId::XAxis) && (id != PickMeshId::YAxis) &&
				(id != PickMeshId::ZNormalPlane) && (id != PickMeshId::YNormalRotate);
			if (updateFlag) {
				updateSection();
			}
		}
	}

	void ClipPlane::onMouseMove()
	{
		if (mState == Stop) {
			bool selectFlag = false;
			mPickMesh = PickMeshId::None;
			for (int i = 0; i < meshInfoCnt; i++) {
				if (renderer->isSelectPolygon("TransformAxis", table[i].blockName)) {
					mPickMesh = i;
					selectFlag = true;
					break;
				}
			}
			if (selectFlag) {
				mState = Hot;
				TransformAxis().setBlockColor(TransformAxis().getBlockId(table[mPickMesh].blockName), hotColor);
			}
		}
		else if (mState == Hot) {
			bool selectFlag = false;
			for (int i = 0; i < meshInfoCnt; i++) {
				if (renderer->isSelectPolygon("TransformAxis", table[i].blockName)) {
					selectFlag = true;
					break;
				}
			}
			if (!selectFlag) {
				mState = Stop;
				TransformAxis().setBlockColor(TransformAxis().getBlockId(table[mPickMesh].blockName), table[mPickMesh].blockColor);
				mPickMesh = PickMeshId::None;
			}
		}
		else if (mState == AxisT) {
			auto& param = renderer->getFrameParam();
			m_internal->transLatePick.apply(param.rayDirection, param.rayOrigin, m_internal->center);
			m_internal->updateEngineUbo = true;
		}
		else if (mState == PlaneT) {
			auto& param = renderer->getFrameParam();
			m_internal->planeTPick.apply(param.rayDirection, param.rayOrigin, m_internal->center);
			m_internal->updateEngineUbo = true;
		}
		else if (mState == AxisR) {
			auto& param = renderer->getFrameParam();
			Eigen::Vector3f dir = table[mPickMesh].meshId == PickMeshId::XNormalRotate ?
				m_internal->yAxis : (table[mPickMesh].meshId == PickMeshId::YNormalRotate ? m_internal->zAxis : m_internal->xAxis);
			m_internal->axisRPick.applyDir(param.rayDirection, param.rayOrigin, dir);
			if (table[mPickMesh].meshId == PickMeshId::XNormalRotate) {
				m_internal->xAxis = dir;
				m_internal->zAxis = m_internal->xAxis.cross(m_internal->yAxis);
			}
			else if (table[mPickMesh].meshId == PickMeshId::YNormalRotate) {
				m_internal->yAxis = dir;
				m_internal->xAxis = m_internal->yAxis.cross(m_internal->zAxis);
			}
			else if (table[mPickMesh].meshId == PickMeshId::ZNormalRotate) {
				m_internal->zAxis = dir;
				m_internal->yAxis = m_internal->zAxis.cross(m_internal->xAxis);
			}
			m_internal->updateEngineUbo = true;
		}
	}

	void ClipPlane::updateSection()
	{
		// The section cap/contour are drawn on the GPU from the clip plane UBO;
		// onUpdate() refreshes the plane each frame during drag.
		m_internal->updateEngineUbo = true;
	}
}
