#ifndef RESOURCES_H_
#define RESOURCES_H_

#include <stdint.h>

#include <string>
#include <unordered_map>

extern std::unordered_map<std::string, int> shaders_offset;

extern std::unordered_map<std::string, int> shaders_len;

const uint8_t* ShaderPackage();
extern int RESOURCES_WIDGETEVENTTRANSLATORH_OFFSET;
extern int RESOURCES_WIDGETEVENTTRANSLATORH_SIZE;
extern int RESOURCES_WIDGETEVENTTRANSLATORCPP_OFFSET;
extern int RESOURCES_WIDGETEVENTTRANSLATORCPP_SIZE;
extern int RESOURCES_WIDGETEVENTH_OFFSET;
extern int RESOURCES_WIDGETEVENTH_SIZE;
extern int RESOURCES_WIDGETEVENTCPP_OFFSET;
extern int RESOURCES_WIDGETEVENTCPP_SIZE;
extern int RESOURCES_WIDGETCALLBACKMAPPERH_OFFSET;
extern int RESOURCES_WIDGETCALLBACKMAPPERH_SIZE;
extern int RESOURCES_WIDGETCALLBACKMAPPERCPP_OFFSET;
extern int RESOURCES_WIDGETCALLBACKMAPPERCPP_SIZE;
extern int RESOURCES_RENDERWINDOWINTERACTORH_OFFSET;
extern int RESOURCES_RENDERWINDOWINTERACTORH_SIZE;
extern int RESOURCES_RENDERWINDOWINTERACTORCPP_OFFSET;
extern int RESOURCES_RENDERWINDOWINTERACTORCPP_SIZE;
extern int RESOURCES_MATHUTILH_OFFSET;
extern int RESOURCES_MATHUTILH_SIZE;
extern int RESOURCES_MATHUTILCPP_OFFSET;
extern int RESOURCES_MATHUTILCPP_SIZE;
extern int RESOURCES_GUIZMOH_OFFSET;
extern int RESOURCES_GUIZMOH_SIZE;
extern int RESOURCES_GUIZMOCPP_OFFSET;
extern int RESOURCES_GUIZMOCPP_SIZE;
extern int RESOURCES_GIZMOOBSERVERH_OFFSET;
extern int RESOURCES_GIZMOOBSERVERH_SIZE;
extern int RESOURCES_GIZMOOBSERVERCPP_OFFSET;
extern int RESOURCES_GIZMOOBSERVERCPP_SIZE;
extern int RESOURCES_GIZMOOBJECTH_OFFSET;
extern int RESOURCES_GIZMOOBJECTH_SIZE;
extern int RESOURCES_GIZMOOBJECTCPP_OFFSET;
extern int RESOURCES_GIZMOOBJECTCPP_SIZE;
extern int RESOURCES_EXECUTECOMMANDH_OFFSET;
extern int RESOURCES_EXECUTECOMMANDH_SIZE;
extern int RESOURCES_EXECUTECOMMANDCPP_OFFSET;
extern int RESOURCES_EXECUTECOMMANDCPP_SIZE;
extern int RESOURCES_EVENTDATAH_OFFSET;
extern int RESOURCES_EVENTDATAH_SIZE;
extern int RESOURCES_EVENTH_OFFSET;
extern int RESOURCES_EVENTH_SIZE;
extern int RESOURCES_EVENTCPP_OFFSET;
extern int RESOURCES_EVENTCPP_SIZE;
extern int RESOURCES_CALLBACKCOMMANDH_OFFSET;
extern int RESOURCES_CALLBACKCOMMANDH_SIZE;
extern int RESOURCES_CALLBACKCOMMANDCPP_OFFSET;
extern int RESOURCES_CALLBACKCOMMANDCPP_SIZE;
extern int RESOURCES_DRIVERH_OFFSET;
extern int RESOURCES_DRIVERH_SIZE;
extern int RESOURCES_DRIVERCPP_OFFSET;
extern int RESOURCES_DRIVERCPP_SIZE;
extern int RESOURCES_DISPATCHERH_OFFSET;
extern int RESOURCES_DISPATCHERH_SIZE;
extern int RESOURCES_DISPATCHERCPP_OFFSET;
extern int RESOURCES_DISPATCHERCPP_SIZE;
extern int RESOURCES_COMMANDSTREAMH_OFFSET;
extern int RESOURCES_COMMANDSTREAMH_SIZE;
extern int RESOURCES_COMMANDSTREAMCPP_OFFSET;
extern int RESOURCES_COMMANDSTREAMCPP_SIZE;
extern int RESOURCES_COMMANDBUFFERQUEUEH_OFFSET;
extern int RESOURCES_COMMANDBUFFERQUEUEH_SIZE;
extern int RESOURCES_COMMANDBUFFERQUEUECPP_OFFSET;
extern int RESOURCES_COMMANDBUFFERQUEUECPP_SIZE;
extern int RESOURCES_CIRCULARBUFFERH_OFFSET;
extern int RESOURCES_CIRCULARBUFFERH_SIZE;
extern int RESOURCES_CIRCULARBUFFERCPP_OFFSET;
extern int RESOURCES_CIRCULARBUFFERCPP_SIZE;
extern int RESOURCES_ABSTRACTWIDGETH_OFFSET;
extern int RESOURCES_ABSTRACTWIDGETH_SIZE;
extern int RESOURCES_ABSTRACTWIDGETCPP_OFFSET;
extern int RESOURCES_ABSTRACTWIDGETCPP_SIZE;
#define RESOURCES_WIDGETEVENTTRANSLATORH_DATA (RESOURCES_PACKAGE + RESOURCES_WIDGETEVENTTRANSLATORH_OFFSET)
#define RESOURCES_WIDGETEVENTTRANSLATORCPP_DATA (RESOURCES_PACKAGE + RESOURCES_WIDGETEVENTTRANSLATORCPP_OFFSET)
#define RESOURCES_WIDGETEVENTH_DATA (RESOURCES_PACKAGE + RESOURCES_WIDGETEVENTH_OFFSET)
#define RESOURCES_WIDGETEVENTCPP_DATA (RESOURCES_PACKAGE + RESOURCES_WIDGETEVENTCPP_OFFSET)
#define RESOURCES_WIDGETCALLBACKMAPPERH_DATA (RESOURCES_PACKAGE + RESOURCES_WIDGETCALLBACKMAPPERH_OFFSET)
#define RESOURCES_WIDGETCALLBACKMAPPERCPP_DATA (RESOURCES_PACKAGE + RESOURCES_WIDGETCALLBACKMAPPERCPP_OFFSET)
#define RESOURCES_RENDERWINDOWINTERACTORH_DATA (RESOURCES_PACKAGE + RESOURCES_RENDERWINDOWINTERACTORH_OFFSET)
#define RESOURCES_RENDERWINDOWINTERACTORCPP_DATA (RESOURCES_PACKAGE + RESOURCES_RENDERWINDOWINTERACTORCPP_OFFSET)
#define RESOURCES_MATHUTILH_DATA (RESOURCES_PACKAGE + RESOURCES_MATHUTILH_OFFSET)
#define RESOURCES_MATHUTILCPP_DATA (RESOURCES_PACKAGE + RESOURCES_MATHUTILCPP_OFFSET)
#define RESOURCES_GUIZMOH_DATA (RESOURCES_PACKAGE + RESOURCES_GUIZMOH_OFFSET)
#define RESOURCES_GUIZMOCPP_DATA (RESOURCES_PACKAGE + RESOURCES_GUIZMOCPP_OFFSET)
#define RESOURCES_GIZMOOBSERVERH_DATA (RESOURCES_PACKAGE + RESOURCES_GIZMOOBSERVERH_OFFSET)
#define RESOURCES_GIZMOOBSERVERCPP_DATA (RESOURCES_PACKAGE + RESOURCES_GIZMOOBSERVERCPP_OFFSET)
#define RESOURCES_GIZMOOBJECTH_DATA (RESOURCES_PACKAGE + RESOURCES_GIZMOOBJECTH_OFFSET)
#define RESOURCES_GIZMOOBJECTCPP_DATA (RESOURCES_PACKAGE + RESOURCES_GIZMOOBJECTCPP_OFFSET)
#define RESOURCES_EXECUTECOMMANDH_DATA (RESOURCES_PACKAGE + RESOURCES_EXECUTECOMMANDH_OFFSET)
#define RESOURCES_EXECUTECOMMANDCPP_DATA (RESOURCES_PACKAGE + RESOURCES_EXECUTECOMMANDCPP_OFFSET)
#define RESOURCES_EVENTDATAH_DATA (RESOURCES_PACKAGE + RESOURCES_EVENTDATAH_OFFSET)
#define RESOURCES_EVENTH_DATA (RESOURCES_PACKAGE + RESOURCES_EVENTH_OFFSET)
#define RESOURCES_EVENTCPP_DATA (RESOURCES_PACKAGE + RESOURCES_EVENTCPP_OFFSET)
#define RESOURCES_CALLBACKCOMMANDH_DATA (RESOURCES_PACKAGE + RESOURCES_CALLBACKCOMMANDH_OFFSET)
#define RESOURCES_CALLBACKCOMMANDCPP_DATA (RESOURCES_PACKAGE + RESOURCES_CALLBACKCOMMANDCPP_OFFSET)
#define RESOURCES_DRIVERH_DATA (RESOURCES_PACKAGE + RESOURCES_DRIVERH_OFFSET)
#define RESOURCES_DRIVERCPP_DATA (RESOURCES_PACKAGE + RESOURCES_DRIVERCPP_OFFSET)
#define RESOURCES_DISPATCHERH_DATA (RESOURCES_PACKAGE + RESOURCES_DISPATCHERH_OFFSET)
#define RESOURCES_DISPATCHERCPP_DATA (RESOURCES_PACKAGE + RESOURCES_DISPATCHERCPP_OFFSET)
#define RESOURCES_COMMANDSTREAMH_DATA (RESOURCES_PACKAGE + RESOURCES_COMMANDSTREAMH_OFFSET)
#define RESOURCES_COMMANDSTREAMCPP_DATA (RESOURCES_PACKAGE + RESOURCES_COMMANDSTREAMCPP_OFFSET)
#define RESOURCES_COMMANDBUFFERQUEUEH_DATA (RESOURCES_PACKAGE + RESOURCES_COMMANDBUFFERQUEUEH_OFFSET)
#define RESOURCES_COMMANDBUFFERQUEUECPP_DATA (RESOURCES_PACKAGE + RESOURCES_COMMANDBUFFERQUEUECPP_OFFSET)
#define RESOURCES_CIRCULARBUFFERH_DATA (RESOURCES_PACKAGE + RESOURCES_CIRCULARBUFFERH_OFFSET)
#define RESOURCES_CIRCULARBUFFERCPP_DATA (RESOURCES_PACKAGE + RESOURCES_CIRCULARBUFFERCPP_OFFSET)
#define RESOURCES_ABSTRACTWIDGETH_DATA (RESOURCES_PACKAGE + RESOURCES_ABSTRACTWIDGETH_OFFSET)
#define RESOURCES_ABSTRACTWIDGETCPP_DATA (RESOURCES_PACKAGE + RESOURCES_ABSTRACTWIDGETCPP_OFFSET)

#endif









